### PR TITLE
Improves code coverage for snippet

### PR DESCRIPTION
**Pull request by hyperwidget**
## Summary
Added two additional testing files to snippet to cover getAllids & makeEmojionBar respectively
Re issue #13:

## Screenshots
N/A

## Checklist
- [ ] I have updated the documentation to reflect my changes
- [x] I have added tests to cover my changes (if relevant)
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by teesloane** [comment]
Awesome, thanks Hunter! @hyperwidget :) 

I hadn't thought to make files for each function seperately, but that makes sense since the files can get long. 

I think that there are some pieces of test materials that we will eventually refactor out, so they can be `require`d instead of of always stubbing out the same thing (default states and whatever). I'm not a testing pro so I'm going to save that for later. 

Thanks for your hard work. Merging now.

**Comment by teesloane** [comment]
lol, also, after merging I noticed this:

```
 it("Should find two ids", () => {
 document.body.innerHTML = _multipleValidElement;
   const currentState = getAllIds(_defaultState);
    expect(currentState.dom.mounts.length).toBe(3);
    expect(currentState.dom.mounts[0].id).toBe("emojion-banana");
    expect(currentState.dom.mounts[1].id).toBe("emojion-skull");
    expect(currentState.dom.mounts[2].id).toBe("emojion-rocket");
});

```
^^ looks like it's checking for three ids (vs. `it should find two ids`) ? If so, I can change this on `development` when I next check in.

**Comment by hyperwidget** [comment]
@teesloane 😅 It WAS two when I started it. I have a problem with never updating my test descriptions. 

As per the file convention, I was just following what was already there with the pipe test; it's not typically something I do

**Comment by teesloane** [comment]
No worries re: description. Thanks again!

**Pull request merged**
