### PR TITLE
Use native elm-css for type-safe CSS.

### PR DESCRIPTION
**Pull request by gilbertkennen**
I blindly moved the hardcoded css into elm-css.

Since we can't change the `html` tag from inside of Elm without ports and trickery, I also added support for [elm-live](https://github.com/tomekwi/elm-live) which allows us to use flags and ports and other such useful things as well as defining our own `index.html` where I added the font scaling style.

### CODE REVIEW

**Comment by teesloane** [comment]
@gilbertkennen This is awesome. I've heard about elm-live but had not thought to test this. I am excited to use elm-css. Hope you don't mind I have a question or two. 

> I blindly moved the hardcoded css into elm-css.

Do you mean you were not able to test? If not, I can pull your branch and give it a test, no problem.

> Regarding elm-live

Is there anything I need to know about booting up the app now? Do we still use `elm-reactor`? ; I'm guessing _no_, since we now have an `index.html` page that mounts the elm file? 

> Font percent size

I noticed that there is font scaling in the elm-css (`[ fontSize (pct 62.5) ]`) as well as in-line in the `index.html` do we need both?

> Regarding importing elm-css 

Would it be easier to expose all of the parts of elm-css (...` import elm-css exposing (..) ` ) ? I'm still new to Elm and am not sure the benefits of seperating out imports (is it to prevent naming collisions?)

Thanks for your hard work and contribution! Really looking forward to merging this.

**Comment by gilbertkennen** [comment]
>

**Comment by gilbertkennen** [comment]
> Do you mean you were not able to test?

No, I mean that I just ported things over without questioning any decisions. The look all seems to be the same for me.

> Is there anything I need to know about booting up the app now?

I added a `project.json` file with the dev dependencies and a script for launching the server. It works for me, but I haven't tested it thoroughly. You should be able to run it with `npm run serve` (or `yarn`).

> Would it be easier to expose all of the parts of elm-css?

This is an area of preference. I almost always prefer to be explicit about exposing imported functions. It prevents name conflicts *and* it makes for better compiler error messages. That said, many people I respect would just `expose (..)` in this instance.

> I noticed that there is font scaling in the elm-css ([ fontSize (pct 62.5) ]) as well as in-line in the index.html do we need both?

Oh, whoops. That was when I was trying out things that didn't work. That function isn't being used anywhere and could be removed.

**Comment by teesloane** [comment]
@gilbertkennen Great, thanks for clarifying. I'm going to go ahead and merge this and remove the font size function when I get a moment :)

**Pull request merged**
