### PR TITLE
Add basic client UI

### PR DESCRIPTION
**Pull request by gilbertkennen**
Implements a basic client UI. No styling has been attempted. The UI displays a list of available emoji which can be toggled for selection and a separate list of selected emoji.

Maximum selection size is enforced. One can click on an item in the selected row and then press the buttons to move its position in the selected order.

To be clear, there is no styling, so it looks horrible and provides poor feedback on what you can do.

### CODE REVIEW

**Comment by teesloane** [comment]
Hi @gilbertkennen . Great work! I pulled your branch and checked it out. I think this is a totally find solution. 

I definitely am pretty lost with your elm code — I won't ask you to comment _every single function_ since you wrote so much (and also, I should be able to work it out with time — but perhaps you could toss in a comment at the top of the zipper module explaining the goal of the file? 

Let me know what you think, and thanks again for your great contribution. I'm glad I had someone else to spearhead structuring the elm app because I'm so new to it and we need someone to take a bit more a leadership role for the start of it.

**Comment by gilbertkennen** [comment]
I added comments to the Zipper. Let me know if it is still confusing.

**Comment by quietcoding** [comment]
Hey @gilbertkennen, 

I think the commenting is great for Zipper, but what about main.elm? I haven't had much chance to dive into this yet, and just from glancing at the code, it looks pretty confusing. Would you mind shedding some light on a newbie like me?

**Comment by gilbertkennen** [comment]
I added a bit of documentation to the types and the helper functions, but the view and update seem fairly self-documenting and I can't think of much to add.

**Comment by teesloane** [comment]
@qazqwezxc If you get a chance research "the elm architecture" — it will probably do a better job than _I_ could for explaining update / view / model. They are key concepts to elm afaik. 

After I merge this I might add some "newbie" friendly comments (for myself included!)

@gilbertkennen thanks for adding the docs!

**Comment by teesloane** [comment]
Wow, @gilbertkennen just looking over the comments you added now and they are EXCELLENT. I have never even heard of a zipper but your docs are very clear and I'm excited to learn more about this. Thanks for taking the time to do this — it benefits everyone who contributes a ton; especially those new to Elm. (I've been writing javascript for 2 years or so and have never even heard of a `zipper`! (All the more reason to do more FP...)

**Comment by gilbertkennen** [comment]
I'm considering splitting that zipper off into its own package, but I am a bit stumped on a name and need to decide how many other functions to include that didn't come naturally based on this project.

I struggled with how much to explain how The Elm Architecture works. For anyone who is interested, [here](https://guide.elm-lang.org/architecture/) is the section of the official guide which talks about it.

**Comment by teesloane** [comment]
@gilbertkennen Interesting - do you mean making the zipper into it's own elm package that anyone can install?

**Comment by gilbertkennen** [comment]
Yes.

**Pull request merged**
